#!/bin/bash

echo "==========================="
echo "Linux Server Health Checker"
echo "==========================="

show_system_info() {
 echo
 echo "=====MEMORY USAGE====="

 echo "Hostname : $(hostname)" 
 echo "User : $USER" 
 echo "Kernel : $(uname -r)" 
 echo "Uptime : $(uptime)"
}

check_disk(){
 echo
 echo "=====DISK USAGE======"
 df -h
}

check_memory(){
 echo
 echo "====MEMORY USAGE====="
 free -h
}

check_website(){
 read -p "Enter Website : " website
 echo "$website checking......"

 if ping -c 3 "$website" > /dev/null 2>&1; then
   echo "Status: Reachable"
 else
   echo "Status: Not Reachable"
 fi
}

#select service
while true
do
    show_header

    echo
    echo "1. Show System Information"
    echo "2. Check Disk Usage"
    echo "3. Check Memory Usage"
    echo "4. Check Website"
    echo "5. Exit"

    echo
    read -p "Choose an option: " choice

    if [ "$choice" -eq 1 ]; then
        show_system_info

    elif [ "$choice" -eq 2 ]; then
        check_disk

    elif [ "$choice" -eq 3 ]; then
        check_memory

    elif [ "$choice" -eq 4 ]; then
        check_website

    elif [ "$choice" -eq 5 ]; then
        echo
        echo "Server Health Checker closed."
        break

    else
        echo
        echo "Invalid option!"
    fi

    echo
    read -p "Press Enter to continue..."
done

